# Generated by Django 3.2.16 on 2022-10-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20221020_1338'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='db',
        ),
    ]
