# Generated by Django 3.2.16 on 2022-11-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20221020_1407'),
        ('blog', '0003_auto_20221020_1406'),
        ('blog', '0005_auto_20221020_1406'),
        ('blog', '0007_alter_post_table'),
    ]

    operations = [
    ]
